# Generated by Django 4.1.3 on 2022-11-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestPerformers',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emp_app.employee')),
                ('award_title', models.CharField(max_length=100)),
                ('date_awarded', models.DateField()),
            ],
            bases=('emp_app.employee',),
        ),
    ]
