# Generated by Django 4.1.3 on 2022-11-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_bestperformers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='department',
            table='emp_app_department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emp_app_employee',
        ),
        migrations.AlterModelTable(
            name='role',
            table='emp_app_role',
        ),
    ]
