# Generated by Django 4.1.3 on 2022-11-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_department_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
