# Generated by Django 4.1.3 on 2022-11-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestperformers',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='bestperformers',
            table='emp_app_bestperformers',
        ),
    ]
