# Generated by Django 4.1.3 on 2022-11-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_alter_bestperformers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='ceo',
            table='emp_app_ceo',
        ),
    ]
