# Generated by Django 4.1.3 on 2022-11-13 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0005_alter_ceo_options_alter_ceo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
