# Generated by Django 4.1.3 on 2022-11-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emp_app_employee',
        ),
    ]
